/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema.informacionGUI;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import sistema.informacionDAL.conexion;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class frmInformacion extends javax.swing.JFrame {

    /**
     * Creates new form frmInformacion
     */
    DefaultTableModel model;
    int xMouse, yMouse;
    
    
    public frmInformacion() {

        initComponents();
        String [] titulos = {" "};
        model = new DefaultTableModel(null, titulos);
        tbInformes.setModel(model);
    /**
     * esquinas redondas
     */   

        setShape(new RoundRectangle2D.Double(0,0, getWidth(), getHeight(), 15, 15));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        rSTableMetro1 = new rojeru_san.complementos.RSTableMetro();
        rSYearDate1 = new rojeru_san.componentes.RSYearDate();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbInformes = new rojeru_san.complementos.RSTableMetro();
        btnInforme1 = new rojerusan.RSButtonMetro();
        btnInforme4 = new rojerusan.RSButtonMetro();
        btnInforme5 = new rojerusan.RSButtonMetro();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(rSTableMetro1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Qué informe deseas conocer?");

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);
        jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setAlignmentX(0.0F);
        jScrollPane3.setAlignmentY(0.0F);

        tbInformes.setAutoCreateRowSorter(true);
        tbInformes.setBackground(new java.awt.Color(255, 255, 255));
        tbInformes.setForeground(new java.awt.Color(255, 255, 255));
        tbInformes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbInformes.setToolTipText("");
        tbInformes.setAlignmentX(0.0F);
        tbInformes.setAlignmentY(0.0F);
        tbInformes.setAltoHead(30);
        tbInformes.setColorBackgoundHead(new java.awt.Color(255, 153, 0));
        tbInformes.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tbInformes.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tbInformes.setColorFilasBackgound2(new java.awt.Color(240, 240, 240));
        tbInformes.setColorFilasForeground1(new java.awt.Color(102, 102, 102));
        tbInformes.setColorFilasForeground2(new java.awt.Color(102, 102, 102));
        tbInformes.setColorSelBackgound(new java.awt.Color(255, 169, 44));
        tbInformes.setFuenteFilas(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbInformes.setFuenteHead(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tbInformes.setGridColor(new java.awt.Color(255, 255, 255));
        tbInformes.setGrosorBordeFilas(2);
        tbInformes.setGrosorBordeHead(2);
        tbInformes.setRowHeight(30);
        tbInformes.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tbInformes.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(tbInformes);

        btnInforme1.setBackground(new java.awt.Color(255, 153, 0));
        btnInforme1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInforme1.setGrosorLinea(2);
        btnInforme1.setHideActionText(true);
        btnInforme1.setLabel("Informe 1");
        btnInforme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInforme1ActionPerformed(evt);
            }
        });

        btnInforme4.setBackground(new java.awt.Color(255, 153, 0));
        btnInforme4.setText("Informe 2");
        btnInforme4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInforme4.setGrosorLinea(2);
        btnInforme4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInforme4ActionPerformed(evt);
            }
        });

        btnInforme5.setBackground(new java.awt.Color(255, 153, 0));
        btnInforme5.setText("Informe 3");
        btnInforme5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInforme5.setGrosorLinea(2);
        btnInforme5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInforme5ActionPerformed(evt);
            }
        });

        rSPanelImage1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelImage1.setImagen(new javax.swing.ImageIcon("C:\\Users\\Luis Tapiero\\Downloads\\Estudio WEB\\Mintic Proyectos\\Ciclo 2\\Reto 5\\Logo-MisionTIC-2022.jpg")); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(170, 170, 170))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnInforme1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnInforme4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnInforme5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(rSPanelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rSPanelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInforme4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInforme5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInforme1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setShape(new RoundRectangle2D.Double(0,0, getWidth(), getHeight(), 10, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void btnInforme5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInforme5ActionPerformed
        conexion objtConexion = new conexion();

        try {
            ResultSet resultado = objtConexion.consultarRegistros("SELECT ID_Compra, Constructora, Banco_Vinculado\n" +
                "FROM Compra c\n" +
                "INNER JOIN Proyecto p ON c.ID_Proyecto = p.ID_Proyecto\n" +
                "WHERE Ciudad='Salento' AND Proveedor='Homecenter';");

            String [] titulos = {"ID Proyecto", "Constructora", "Banco vinculado" };
            model = new DefaultTableModel(null, titulos);
            tbInformes.setModel(model);

            while (resultado.next()) {
                System.out.println(resultado.getString("ID_Compra"));
                System.out.println(resultado.getString("Constructora"));
                System.out.println(resultado.getString("Banco_Vinculado"));

                Object [] usuario = {resultado.getString("ID_Compra"),resultado.getString("Constructora"), resultado.getString("Banco_Vinculado")};
                model.addRow(usuario);

            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnInforme5ActionPerformed

    private void btnInforme4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInforme4ActionPerformed
        conexion objtConexion = new conexion();

        try {
            ResultSet resultado = objtConexion.consultarRegistros("SELECT ID_Proyecto, Constructora, Numero_Habitaciones, Ciudad\n" +
                "FROM Proyecto\n" +
                "WHERE Ciudad IN ('Santa Marta','Cartagena','Barranquilla')\n" +
                "AND Clasificacion = 'Casa Campestre';");

            String [] titulos = {"ID Proyecto", "Constructora", "Numero habitaciones", "Ciudad" };
            model = new DefaultTableModel(null, titulos);
            tbInformes.setModel(model);

            while (resultado.next()) {
                System.out.println(resultado.getString("ID_Proyecto"));
                System.out.println(resultado.getString("Constructora"));
                System.out.println(resultado.getString("Numero_Habitaciones"));
                System.out.println(resultado.getString("Ciudad"));

                Object [] usuario = {resultado.getString("ID_Proyecto"),resultado.getString("Constructora"), resultado.getString("Numero_Habitaciones"), resultado.getString("Ciudad")};
                model.addRow(usuario);

            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnInforme4ActionPerformed

    private void btnInforme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInforme1ActionPerformed
        conexion objtConexion = new conexion();

        try {
            ResultSet resultado = objtConexion.consultarRegistros("SELECT ID_Lider, Nombre, Primer_Apellido, Ciudad_Residencia\n" +
                "FROM Lider\n" +
                "ORDER BY Ciudad_Residencia;");

            String [] titulos = {"ID Lider", "Nombre", "Primer Apellido", "Ciudad residencia" };
            model = new DefaultTableModel(null, titulos);
            tbInformes.setModel(model);

            while (resultado.next()) {
                System.out.println(resultado.getString("ID_Lider"));
                System.out.println(resultado.getString("Nombre"));
                System.out.println(resultado.getString("Primer_Apellido"));
                System.out.println(resultado.getString("Ciudad_Residencia"));

                Object [] usuario = {resultado.getString("ID_Lider"),resultado.getString("Nombre"), resultado.getString("Primer_Apellido"), resultado.getString("Ciudad_Residencia")};
                model.addRow(usuario);

            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnInforme1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked
    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInformacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro btnInforme1;
    private rojerusan.RSButtonMetro btnInforme4;
    private rojerusan.RSButtonMetro btnInforme5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private rojerusan.RSPanelImage rSPanelImage1;
    private rojeru_san.complementos.RSTableMetro rSTableMetro1;
    private rojeru_san.componentes.RSYearDate rSYearDate1;
    private rojeru_san.complementos.RSTableMetro tbInformes;
    // End of variables declaration//GEN-END:variables
}
